### ISSUE TITLE
'Unterminated quoted string' when running in Docker

### ISSUE THREAD

**Issue by seanemmer** [meanjs/mean-seo#16]
Error code is as follows:

```
at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
Error: Command failed: /home/agepath/node_modules/mean-seo/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /home/agepath/node_modules/mean-seo/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
```

**Comment by agepath** [comment]
Is this project still alive?  I believe I've found a solution (use phantomjs-bin instead of phantomjs) and would like to submit a pull request.

**Comment by seanemmer** [comment]
Is this project still alive? I believe I've found a solution (use phantomjs-bin instead of phantomjs) and would like to submit a pull request.
